### PR TITLE
fix: interval not being cleared

### LINKED ISSUE #20: Interval does not get cleared on anything other than 'completed' status
The intervals do not get cleared when resetting / aborting the gateway due to an erroneous   variable assignment conditional statement in the listener.

**Expected Behavior**
When calling the `.reset()` method, either directly or via `__abort()`, the interval should be cleared.

**Current Behavior**
The only time the interval gets cleared is when a payment is completed. 

**Possible Solution**
Change the variable assignment in the `__mountListener` method  (`this.started`) to the same assignment as in the `reset()` method (`this.data.started`).

**Steps to Reproduce (for bugs)**
1. Create a project with ARK Pay
2. Try to stop the gateway with `.reset()`, or force an error
3. Look at your dev tools and notice the gateway is still fetching requests every second

A PR has been created. 

**Your environment**  
- ARK Pay v0.1.12
- node v10.15.3
- npm v6.9.0
- W10

### PR DESCRIPTION
**Pull request by Lemii**
Resolves #20

This PR fixes a small but **breaking** bug that caused the interval not being cleared on `reset()` / `abort()`.

It took me quite a while only to find out that in the end it was a very small (but devastating) error in this package itself.

## What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactor
- [ ] Performance
- [ ] Tests
- [ ] Build
- [ ] Documentation
- [ ] Code style update
- [ ] Continuous Integration
- [ ] Other, please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Does this PR release a new version?

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `develop` branch, _not_ the `master` branch
- [x] All tests are passing
- [ ] New/updated tests are included

### CODE REVIEW

**Comment by ghost** [comment]
**Thanks for submitting this pull request!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by faustbrian** [comment]
@Lemii Will merge if the changelog and version bump are removed.

**Comment by Lemii** [comment]
> @Lemii Will merge if the changelog and version bump are removed.

The changelog and version bump is removed @faustbrian

**Review by faustbrian — APPROVED** [review]

**Comment by ghost** [comment]
A contributor has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Comment by ghost** [comment]
Your pull request has been merged and marked as tier 4. _It will earn you $10 USD._

**Comment by faustbrian** [comment]
> > @Lemii Will merge if the changelog and version bump are removed.
> 
> The changelog and version bump is removed @faustbrian

Thanks, merged 👍

**Pull request merged**
